name: p5_fusion_dart
description: Library that can calculate fusions in Persona 5 game.
version: 1.0.3

documentation: https://alfasquad.github.io/p5_fusion_dart/

homepage: https://github.com/AlfaSquaD/p5_fusion_dart

environment:
  sdk: '>=2.14.4 <3.0.0'


dependencies:
  path: ^1.8.0
  equatable: ^2.0.3

dev_dependencies:
  lints: ^1.0.0
  test: ^1.19.3